// Generated list of Lucide icons (ISC licence) with Arabic keywords used for auto-selection.
import {
  Droplet, Droplets, Waves, Leaf, Sprout, TreePine, Sun, Moon, Cloud, CloudRain, Snowflake, Wind, Thermometer, Flame, Zap, Lightbulb, BookOpen, GraduationCap, School, Pencil, Brain, BrainCircuit, Microscope, FlaskConical, Atom, Calculator, Globe, Earth, Map, MapPin, Mountain, Recycle, Trash2, Heart, HeartPulse, Activity, Stethoscope, Pill, Syringe, Apple, Carrot, Salad, Utensils, Coffee, Milk, Dumbbell, Bike, Footprints, Bed, Smile, Frown, Users, User, Baby, House, Building2, Factory, Car, Bus, Plane, Train, Ship, Fuel, BatteryCharging, Wifi, Smartphone, Laptop, Monitor, Cpu, Bot, Code, Database, Shield, ShieldCheck, Lock, Key, TriangleAlert, CircleCheck, CircleX, Info, CircleHelp, Star, Trophy, Target, Flag, Rocket, TrendingUp, TrendingDown, ChartColumn, ChartPie, ChartLine, Coins, Wallet, DollarSign, ShoppingCart, Briefcase, Clock, Calendar, Timer, Hourglass, MessageCircle, Mail, Phone, Megaphone, Camera, Music, Film, Palette, Hand, HandHeart, Handshake, Scale, Gavel, Landmark, Fish, Bird, Dog, Cat, PawPrint, Umbrella, Sparkles, Gift, Puzzle, Layers, ListChecks, ListOrdered, ArrowLeftRight, Quote, PartyPopper, ThumbsUp, Eye, Search, Settings, Wrench, Hammer, Package, Truck, Newspaper, Video, Mic, Headphones, Gamepad2, Medal, Award, Crown, Gem, Shirt, Bug, Biohazard, CigaretteOff, Telescope, Orbit, Satellite, Wheat, Egg, Sandwich, History, Milestone, Route, Compass, Scroll, Library, NotebookPen, Languages, Goal, Hospital, Ambulance, Percent, Gauge,
  type IconNode,
} from 'lucide';

export interface IconDef {
  id: string;
  node: IconNode;
  keywords: string[];
}

const def = (id: string, node: IconNode, keywords: string): IconDef => ({ id, node, keywords: keywords.split(' ') });

export const ICONS: IconDef[] = [
  def('droplet', Droplet, 'ماء مياه قطره سائل شرب ري'),
  def('droplets', Droplets, 'رطوبه امطار ترطيب سوائل'),
  def('waves', Waves, 'بحر محيط موج انهار نهر'),
  def('leaf', Leaf, 'بيئه طبيعه نبات اخضر ورق'),
  def('sprout', Sprout, 'نمو زراعه بذور غرس تطور'),
  def('tree-pine', TreePine, 'شجر غابه اشجار تشجير'),
  def('sun', Sun, 'شمس صباح حراره طاقه شمسيه صيف'),
  def('moon', Moon, 'قمر ليل نوم رمضان مساء'),
  def('cloud', Cloud, 'سحاب طقس غيوم سحابه'),
  def('cloud-rain', CloudRain, 'مطر امطار شتاء'),
  def('snowflake', Snowflake, 'ثلج برد بروده'),
  def('wind', Wind, 'رياح هواء تنفس'),
  def('thermometer', Thermometer, 'درجه حراره احترار مناخ حمي'),
  def('flame', Flame, 'نار حريق احتراق سعرات'),
  def('zap', Zap, 'كهرباء طاقه سرعه قوه'),
  def('lightbulb', Lightbulb, 'فكره افكار ابداع نصيحه نصائح اقتراح'),
  def('book-open', BookOpen, 'كتاب قراءه درس دروس تعلم معرفه'),
  def('graduation-cap', GraduationCap, 'تعليم طالب طلاب جامعه تخرج دراسه'),
  def('school', School, 'مدرسه مدارس صف فصل'),
  def('pencil', Pencil, 'كتابه قلم واجب اختبار امتحان'),
  def('brain', Brain, 'عقل دماغ تفكير ذاكره تركيز'),
  def('brain-circuit', BrainCircuit, 'ذكاء اصطناعي ai تعلم الي'),
  def('microscope', Microscope, 'علم علوم بحث مختبر خليه'),
  def('flask-conical', FlaskConical, 'كيمياء تجربه تجارب معمل'),
  def('atom', Atom, 'ذره فيزياء نووي'),
  def('calculator', Calculator, 'حساب رياضيات ارقام معادله'),
  def('globe', Globe, 'عالم دول دولي عالمي'),
  def('earth', Earth, 'ارض كوكب كره'),
  def('map', Map, 'خريطه جغرافيا منطقه'),
  def('map-pin', MapPin, 'موقع مكان مدينه'),
  def('mountain', Mountain, 'جبل جبال تحدي قمه'),
  def('recycle', Recycle, 'تدوير اعاده استدامه'),
  def('trash-2', Trash2, 'نفايات قمامه هدر'),
  def('heart', Heart, 'حب قلب صحه عاطفه'),
  def('heart-pulse', HeartPulse, 'نبض قلب ضغط دم'),
  def('activity', Activity, 'نشاط حركه لياقه'),
  def('stethoscope', Stethoscope, 'طبيب طب علاج مريض'),
  def('pill', Pill, 'دواء ادويه فيتامين حبوب'),
  def('syringe', Syringe, 'لقاح تطعيم حقنه'),
  def('apple', Apple, 'فاكهه تفاح غذاء صحي'),
  def('carrot', Carrot, 'خضار خضروات'),
  def('salad', Salad, 'غذاء تغذيه طعام صحي وجبه'),
  def('utensils', Utensils, 'اكل طعام مطعم وجبات'),
  def('coffee', Coffee, 'قهوه شاي كافيين مشروب'),
  def('milk', Milk, 'حليب البان كالسيوم'),
  def('dumbbell', Dumbbell, 'رياضه تمارين تمرين عضلات'),
  def('bike', Bike, 'دراجه'),
  def('footprints', Footprints, 'مشي خطوات قدم'),
  def('bed', Bed, 'نوم راحه سرير'),
  def('smile', Smile, 'سعاده ابتسامه سعيد نفسيه'),
  def('frown', Frown, 'حزن قلق اكتئاب توتر'),
  def('users', Users, 'مجتمع ناس فريق اسره اشخاص سكان'),
  def('user', User, 'شخص فرد انسان'),
  def('baby', Baby, 'طفل اطفال رضيع'),
  def('house', House, 'بيت منزل منازل سكن'),
  def('building-2', Building2, 'مدن شركه مبني'),
  def('factory', Factory, 'مصنع صناعه انتاج تلوث'),
  def('car', Car, 'سياره سيارات قياده مرور'),
  def('bus', Bus, 'حافله نقل مواصلات'),
  def('plane', Plane, 'طائره سفر طيران رحله'),
  def('train', Train, 'قطار'),
  def('ship', Ship, 'سفينه ميناء شحن'),
  def('fuel', Fuel, 'وقود بنزين نفط بترول'),
  def('battery-charging', BatteryCharging, 'بطاريه شحن'),
  def('wifi', Wifi, 'انترنت شبكه اتصال'),
  def('smartphone', Smartphone, 'هاتف جوال موبايل تطبيق'),
  def('laptop', Laptop, 'حاسوب كمبيوتر'),
  def('monitor', Monitor, 'شاشه شاشات'),
  def('cpu', Cpu, 'تقنيه تكنولوجيا معالج'),
  def('bot', Bot, 'روبوت اتمته'),
  def('code', Code, 'برمجه كود مطور'),
  def('database', Database, 'بيانات معلومات'),
  def('shield', Shield, 'حمايه امن وقايه'),
  def('shield-check', ShieldCheck, 'امان سلامه موثوق'),
  def('lock', Lock, 'خصوصيه قفل سر'),
  def('key', Key, 'مفتاح حل'),
  def('triangle-alert', TriangleAlert, 'تحذير خطر انتباه مخاطر احذر'),
  def('circle-check', CircleCheck, 'صحيح نجاح افعل'),
  def('circle-x', CircleX, 'خطا تجنب لا تفعل ممنوع'),
  def('info', Info, 'معلومه تعريف'),
  def('circle-help', CircleHelp, 'سؤال لماذا كيف ماذا'),
  def('star', Star, 'نجم تميز مميز'),
  def('trophy', Trophy, 'فوز انجاز بطوله جائزه'),
  def('target', Target, 'هدف اهداف'),
  def('flag', Flag, 'بدايه انطلاق علم وطن'),
  def('rocket', Rocket, 'اطلاق اطلق نمو سريع فضاء'),
  def('trending-up', TrendingUp, 'زياده ارتفاع نمو تحسن'),
  def('trending-down', TrendingDown, 'انخفاض تراجع نقص'),
  def('chart-column', ChartColumn, 'احصاء احصائيات نسبه ارقام'),
  def('chart-pie', ChartPie, 'نسب توزيع حصه'),
  def('chart-line', ChartLine, 'تطور اتجاه منحني'),
  def('coins', Coins, 'مال نقود توفير ادخار'),
  def('wallet', Wallet, 'ميزانيه محفظه مصروف'),
  def('dollar-sign', DollarSign, 'دولار سعر تكلفه اقتصاد'),
  def('shopping-cart', ShoppingCart, 'تسوق شراء متجر'),
  def('briefcase', Briefcase, 'عمل وظيفه مهنه اعمال'),
  def('clock', Clock, 'وقت ساعه'),
  def('calendar', Calendar, 'تاريخ موعد يوم سنه'),
  def('timer', Timer, 'مده دقيقه دقائق'),
  def('hourglass', Hourglass, 'انتظار صبر زمن'),
  def('message-circle', MessageCircle, 'محادثه تواصل رساله'),
  def('mail', Mail, 'بريد ايميل'),
  def('phone', Phone, 'اتصال مكالمه'),
  def('megaphone', Megaphone, 'اعلان حمله توعيه تسويق'),
  def('camera', Camera, 'تصوير صوره صور'),
  def('music', Music, 'موسيقي اغنيه صوت'),
  def('film', Film, 'فيلم سينما'),
  def('palette', Palette, 'فن الوان رسم تصميم'),
  def('hand', Hand, 'يد توقف'),
  def('hand-heart', HandHeart, 'تطوع خير صدقه عطاء مساعده'),
  def('handshake', Handshake, 'تعاون شراكه اتفاق'),
  def('scale', Scale, 'عدل توازن قانون'),
  def('gavel', Gavel, 'محكمه قضاء حكم'),
  def('landmark', Landmark, 'حكومه دوله تاريخ اثار'),
  def('fish', Fish, 'سمك اسماك صيد'),
  def('bird', Bird, 'طيور طائر'),
  def('dog', Dog, 'كلب حيوان'),
  def('cat', Cat, 'قطه قطط'),
  def('paw-print', PawPrint, 'حيوانات اليفه'),
  def('umbrella', Umbrella, 'مظله تامين'),
  def('sparkles', Sparkles, 'جديد سحر مميزات'),
  def('gift', Gift, 'هديه هدايا'),
  def('puzzle', Puzzle, 'لغز حل مشكله'),
  def('layers', Layers, 'مراحل طبقات مستويات'),
  def('list-checks', ListChecks, 'قائمه مهام'),
  def('list-ordered', ListOrdered, 'ترتيب خطوات'),
  def('arrow-left-right', ArrowLeftRight, 'مقارنه مقابل فرق بين'),
  def('quote', Quote, 'اقتباس قال حكمه قول'),
  def('party-popper', PartyPopper, 'احتفال عيد مناسبه'),
  def('thumbs-up', ThumbsUp, 'اعجاب ممتاز جيد'),
  def('eye', Eye, 'عين نظر رؤيه بصر'),
  def('search', Search, 'بحث اكتشاف'),
  def('settings', Settings, 'اعدادات ضبط نظام'),
  def('wrench', Wrench, 'صيانه اصلاح'),
  def('hammer', Hammer, 'بناء انشاء'),
  def('package', Package, 'منتج منتجات'),
  def('truck', Truck, 'توصيل شحنه'),
  def('newspaper', Newspaper, 'اخبار خبر صحافه'),
  def('video', Video, 'فيديو'),
  def('mic', Mic, 'بودكاست تسجيل ميكروفون'),
  def('headphones', Headphones, 'استماع سماعه'),
  def('gamepad-2', Gamepad2, 'العاب لعب'),
  def('medal', Medal, 'ميداليه'),
  def('award', Award, 'شهاده تكريم'),
  def('crown', Crown, 'ملك قياده قائد'),
  def('gem', Gem, 'قيمه ثمين'),
  def('shirt', Shirt, 'ملابس ازياء'),
  def('bug', Bug, 'حشرات حشره'),
  def('biohazard', Biohazard, 'فيروس عدوي وباء امراض'),
  def('cigarette-off', CigaretteOff, 'تدخين سجائر'),
  def('telescope', Telescope, 'فلك نجوم'),
  def('orbit', Orbit, 'مدار كواكب'),
  def('satellite', Satellite, 'قمر صناعي'),
  def('wheat', Wheat, 'قمح حبوب خبز'),
  def('egg', Egg, 'بيض بروتين'),
  def('sandwich', Sandwich, 'فطور'),
  def('history', History, 'ماضي قديم تاريخي'),
  def('milestone', Milestone, 'مرحله محطه'),
  def('route', Route, 'طريق مسار رحله'),
  def('compass', Compass, 'اتجاه استكشاف'),
  def('scroll', Scroll, 'وثيقه مخطوطه'),
  def('library', Library, 'مكتبه'),
  def('notebook-pen', NotebookPen, 'ملاحظات تلخيص ملخص'),
  def('languages', Languages, 'لغه لغات ترجمه'),
  def('goal', Goal, 'غايه'),
  def('hospital', Hospital, 'مستشفي'),
  def('ambulance', Ambulance, 'اسعاف طوارئ'),
  def('percent', Percent, 'بالمئه خصم'),
  def('gauge', Gauge, 'قياس سرعه اداء مستوي'),
];
